export const images = [
    {
      id: 1,
      src:"../../src/assets/1.png",
      alt: 'Image 1',
      link: 'https://google.com',
    },
    {
      id: 2,
      src:"../../src/assets/2.png",
      alt: 'Image 2',
      link: 'https://google.com',
     
      
    },{ id: 3,
      src:"../../src/assets/3.png",
        alt: 'Image 3',
        link: 'https://google.com'},
        {id: 4,
          src:"../../src/assets/4.png",
          alt: 'Image 4',
            link: 'https://google.com'},{id: 5,
            src:"../../src/assets/5.png",
            alt: 'Image 4',
            link: 'https://google.com'},
            {id: 6,
              src:"../../src/assets/6.png",
              alt: 'Image 4',
                link: 'https://google.com',},
                {id: 7,
                  src:"../../src/assets/7.png",
                  alt: 'Image 4',
                    link: 'https://google.com',},  {id: 8,
                    src:"../../src/assets/8.png",
                    alt: 'Image 4',
                      link: 'https://google.com',},  {id: 9,
                      src:"../../src/assets/9.png",
                      alt: 'Image 4',
                        link: 'https://google.com',},  {id: 10,
                        src:"../../src/assets/10.png",
                        alt: 'Image 4',
                          link: 'https://google.com',} , {id: 11,
                          src:"../../src/assets/11.png",
                          alt: 'Image 4',
                            link: 'https://google.com',},  {id: 12,
                            src:"../../src/assets/12.png",
                            alt: 'Image 4',
                              link: 'https://google.com',}
    // Add more images with respective links
  ];